services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: crm-graphql-api

    ports:
      - "4000:4000"

    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/crm
      CORS_ORIGIN: http://localhost:4000
      REDIS_URL: redis://redis:6379

    depends_on:
      mongo:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped

    read_only: true

    tmpfs:
      - /tmp

    cap_drop:
      - ALL


  mongo:
    image: mongo:8

    container_name: crm-graphql-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')"
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


  redis:
    image: redis:8-alpine

    container_name: crm-graphql-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:
  mongo_data:
  redis_data: